Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [1]:
import numpy as np

In [29]:
ran1= np.random.randint(10, 100, (50))

In [30]:
ran1

array([58, 86, 88, 10, 46, 71, 20, 16, 16, 79, 64, 78, 60, 81, 41, 29, 71,
       46, 53, 21, 13, 17, 99, 75, 72, 81, 76, 48, 17, 95, 37, 79, 90, 56,
       39, 38, 17, 37, 69, 90, 89, 39, 63, 41, 63, 84, 40, 91, 87, 18],
      dtype=int32)

In [31]:
ran1 % 5 == 0

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False])

In [43]:
ran2

array([ 4,  2, 18, 14, 12, 19,  7, 19, 20,  3,  5, 15, 18, 13,  3, 11,  6,
       20,  9, 12, 16,  8,  7, 10, 13, 19, 16,  9,  9, 13], dtype=int32)

In [33]:
condicion = ran1 % 5 == 0

In [34]:
multiplos_5 = ran1[condicion]

In [35]:
multiplos_5

array([10, 20, 60, 75, 95, 90, 90, 40], dtype=int32)

Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [36]:
ran2= np.random.randint(1, 21, (30))

In [38]:
ran2.size

30

In [44]:
condicion2 = ran2 % 2 != 0

In [45]:
condicion2

array([False, False, False, False, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True, False, False,
        True, False, False, False,  True, False,  True,  True, False,
        True,  True,  True])

In [46]:
impares = ran2[condicion2]
impares

array([19,  7, 19,  3,  5, 15, 13,  3, 11,  9,  7, 13, 19,  9,  9, 13],
      dtype=int32)

Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [54]:
import numpy as np

# Creamos 10 números entre 0 y 5
array_decimales = np.random.uniform(1, 24, 20)

# Redondeamos a 2 decimales
array_final = np.round(array_decimales, 2)

print(array_final)

[19.03 15.23 18.27  7.82 22.9   9.32 12.21  3.23  8.45 12.55 20.67 18.78
 10.76 12.27  5.71 14.16 12.59  1.32  3.07 12.17]


In [64]:
# Creamos la matriz 2D
# low=10, high=50, size=(filas, columnas)
matriz_2d = np.random.uniform(1, 9, size=(4, 6))

# Redondeamos a 2 decimales
matriz_final = np.round(matriz_2d, 3)

print("Mi matriz de 4x6 con decimales:")
print(matriz_final)

Mi matriz de 4x6 con decimales:
[[1.192 2.89  4.155 5.577 3.006 6.187]
 [2.578 4.855 4.521 7.563 3.556 7.162]
 [1.833 6.77  4.513 5.988 3.688 6.466]
 [6.602 4.433 3.932 7.51  8.392 7.35 ]]


In [67]:
redondeoultima = np.round(matriz_final[-1], 1)

In [68]:
redondeoultima

array([6.6, 4.4, 3.9, 7.5, 8.4, 7.4])

Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal

In [73]:
# low=10, high=50, size=(filas, columnas)
matriz_3d = np.random.uniform(0, 1, size=(2, 3, 5))

# Redondeamos a 1 decimal
matriz_3dfinal = np.round(matriz_3d, 1)

print(matriz_3dfinal)

[[[0.4 0.5 0.8 0.1 0.9]
  [1.  0.9 0.5 0.5 0.8]
  [0.6 0.2 0.1 0.4 0.1]]

 [[0.7 0.7 0.  0.6 0.4]
  [0.3 0.  0.1 0.6 0.7]
  [0.7 0.6 0.8 0.  0.4]]]


In [74]:
matriz_3dfinal.ndim

3